# For scenario 7. Slow to mark a dead node unhealthy.
events {}
http {
  upstream app_all {
    server app1:3000 max_fails=10 fail_timeout=60s;
    server app2:3000 max_fails=10 fail_timeout=60s;
    server app3:3000 max_fails=10 fail_timeout=60s;
  }
  server {
    listen 80;
    location / {
      proxy_pass http://app_all;
      proxy_connect_timeout 5s;
      proxy_read_timeout 10s;
    }
  }
}
