events {}

http {
  upstream app_all {
    server app1:3000 max_fails=3 fail_timeout=10s;
    server app2:3000 max_fails=3 fail_timeout=10s;
    server app3:3000 max_fails=3 fail_timeout=10s;
  }

  upstream app_canary {
    server app1:3000 weight=3;
    server app2:3000 weight=3;
    server app3:3000 weight=3;
    server app-v2-canary:3000 weight=1;
  }

  server {
    listen 80;

    location /canary/ {
      rewrite ^/canary(/.*)$ $1 break;
      proxy_pass http://app_canary;
    }

    location / {
      proxy_pass http://app_all;
      proxy_connect_timeout 2s;
      proxy_read_timeout 5s;
    }
  }
}
